[workspace]
resolver = "3"
members = [
  "crates/app",
  "crates/core",
  "crates/meta-parser",
  "crates/favicon-fetcher",
  "crates/favicon-server",
]

[workspace.package]
version = "0.29.0"
authors = ["andots"]
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.97"
log = "0.4.26"
reqwest = "0.12.12"
serde = "1.0.219"
serde_json = "1.0.140"
strum = "0.27.1"
thiserror = "2.0.12"
url = "2.5.4"
tokio = "1.44.0"

# internal
mejiro-core = { path = "./crates/core" }
meta-parser = { path = "./crates/meta-parser" }
favicon-fetcher = { path = "./crates/favicon-fetcher" }
favicon-server = { path = "./crates/favicon-server" }

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
incremental = false
opt-level = "s"
strip = true
