[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-send-page-title",
  "allow-send-page-url",
  "allow-get-external-webview-title",
  "allow-history-back",
  "allow-history-forward",
]
